name: Dev Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Preuzimanje koda
        uses: actions/checkout@v4

      - name: Podesavanje Node.js okruzenja
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Instalacija zavisnosti
        run: npm install

      - name: Pokretanje Unit testova
        run: npm run test:unit

      - name: Kreiranje Docker slike za Dev
        run: docker build -t aplikacija:dev-${{ github.sha }} .
